   /* This Pl sql script prints the date   */
DECLARE
V_CURR_DATE DATE;
TYPE 
BEGIN
SELECT CURRENT_TIMESTAMP INTO V_CURR_DATE FROM DUAL ;

DBMS_OUTPUT.PUT_LINE('The current date '||V_CURR_DATE);

EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;
   /
