 /* This Pl sql script prints the date   */
DECLARE
V_CURR_DATE DATE;

BEGIN
SELECT CURRENT_TIMESTAMP INTO V_CURR_DATE FROM DUAL ;

DBMS_OUTPUT.WRITE_LINE("The current date "||V_CURR_DATE);

EXCEPTION
WHEN OTHERS
DBMS_OUTPUT.WRITE_LINE(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;
END ;
