
from toroman import Solution
s=Solution()

print(s.intToRoman( 1 ))
print(s.intToRoman( 2 ))
print(s.intToRoman( 3 ))
print(s.intToRoman( 4 ))
print(s.intToRoman( 5 ))
print(s.intToRoman( 6 ))
print(s.intToRoman( 7 ))
print(s.intToRoman( 8 ))
print(s.intToRoman( 9 ))
print(s.intToRoman( 10 ))
print(s.intToRoman( 11 ))
print(s.intToRoman( 12 ))
print(s.intToRoman( 13 ))
print(s.intToRoman( 14 ))
print(s.intToRoman( 15 ))
print(s.intToRoman( 16 ))
print(s.intToRoman( 17 ))
print(s.intToRoman( 18 ))
print(s.intToRoman( 19 ))
print(s.intToRoman( 20 ))
print(s.intToRoman( 21 ))
print(s.intToRoman( 22 ))
print(s.intToRoman( 23 ))
print(s.intToRoman( 24 ))
print(s.intToRoman( 25 ))
print(s.intToRoman( 26 ))
print(s.intToRoman( 27 ))
print(s.intToRoman( 28 ))
print(s.intToRoman( 29 ))
print(s.intToRoman( 30 ))
print(s.intToRoman( 31 ))
print(s.intToRoman( 32 ))
print(s.intToRoman( 33 ))
print(s.intToRoman( 34 ))
print(s.intToRoman( 35 ))
print(s.intToRoman( 36 ))
print(s.intToRoman( 37 ))
print(s.intToRoman( 38 ))
print(s.intToRoman( 39 ))
print(s.intToRoman( 40 ))

