server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:8087
          predicates:
            - Path=/inventory/**
          #api/v2/inventory/assets
          filters:
            - StripPrefix=1
        - id: test
          uri: http://localhost:8081
          predicates:
            - Path=/employees/**
          filters:
            - AddRequestHeader=X-Gateway-Tag, Employee-Gateway
            - RewritePath=/employees/(?<segment>.*), /api/v2/employees/${segment}
            - name: Retry
              args:
                  retries: 3
                  statuses:
                    - INTERNAL_SERVER_ERROR
                    - SERVICE_UNAVAILABLE
                    - GATEWAY_TIMEOUT
                    - UNAUTHORIZED
                  methods:
                    - GET
                  backoff:
                    firstBackoff: 100ms
                    maxBackoff: 500ms
                    factor: 2
                    basedOnPreviousValue: true

        - id: employee-service
          uri: http://localhost:8081
          predicates:
            - Path=/emp/api/v2/employees/**       # e.g., /employees, /employees/1
          filters:
            - name: Retry
              args:
                retries: 5
                statuses: NOT_FOUND , UNAUTHORIZED
                methods: GET,POST
            - StripPrefix=1            # Remove '/employees' from path when forwarding



# Optional for logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG