package com.example.order.model;

public enum OrderStatus {
    ORDER_PLACED,
    INVENTORY_VALIDATE,
    PAYMENT_REQUESTED,
    ORDER_CREATED,
    INVENTORY_RESERVED,
    PAYMENT_PROCESSED,
    SHIPMENT_REQUESTED,
    SHIPMENT_CONFIRMED,
    INVENTORY_RESERVATION_FAILED,
    FAILED,
    PAYMENT_FAILED,
    INVENTORY_RELEASE
}
