
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT, SALARY) VALUES (1, 'Alice', 'HR', 50000);
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT, SALARY) VALUES (2, 'Bob', 'IT', 70000);
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT, SALARY) VALUES (3, 'Charlie', 'IT', 80000);
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT, SALARY) VALUES (4, 'David', 'HR', 60000);
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT, SALARY) VALUES (5, 'Eve', 'Sales', 75000);
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT, SALARY) VALUES (6, 'Frank', 'Sales', 72000);

COMMIT;

