CREATE TABLE PROJECTS (
PROJECT_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
PROJECT_DESC VARCHAR(30) NOT NULL,
PROJECT_REF VARCHAR(30) NOT NULL,
PROJECT_STATUS VARCHAR(50),
UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)



